### ISSUE TITLE
JSON Files in VizWiz-Classification Dataset

### ISSUE THREAD

**Issue by hayakae** [rezaakb/VizWiz-Classification-Dataset#6]
Thank you for wonderful work!
I would like to use the training and validation datasets. Specifically, I am looking to obtain the correct labels for each image in these datasets.

While the JSON files listed on the webpage include the filenames of each image, such as "VizWiz_train_00002601.jpg", they do not appear to contain the corresponding WordNet IDs or labels for each image. Could you please provide information on how to obtain these labels?
Thank you for your assistance, and I look forward to your response.

**Comment by rezaakb** [comment]
I appreciate your interest in our work! We did not publish the labels, but you can run the evaluation on your predictions using the [EvalAI](https://eval.ai/web/challenges/challenge-page/1999/overview) server.

**Comment by hayakae** [comment]
Thank you for your prompt response.

I understand that the labels for the test data can be obtained through the EvalAI server. However, I am specifically interested in obtaining the correct labels for the training dataset.

Without access to the correct labels for the training data, it would be impossible to train the model effectively. Could you please confirm whether it is possible to provide the labels for the training data?

**Comment by rezaakb** [comment]
Our dataset consists only of test data and currently does not have any annotations for the training data. Thank you.

**Comment by hayakae** [comment]
I believe that this dataset will be very useful in the field of machine learning in the future. Although the current dataset is designed for zero-shot classification tasks, I am looking forward to the release of labeled training data.

Thank you very much for your assistance.
